services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.11.0 # 
    container_name: mealie
    restart: unless-stopped
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - /home/roman/configs/mealie/data:/app/data/
    environment:
      SMTP_HOST: smtp.gmail.com
      SMTP_FROM_EMAIL: example@gmail.com
      SMTP_USER: roma.steciuk@gmail.com
      SMTP_PASSWORD: test_password
      THEME_LIGHT_PRIMARY: #9999ff
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Canada/Toronto
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://example.com
