version: '3.3'
services:
  linuxserver:
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - '/home/roman/configs/plex:/config'
      - '/mnt/share/Media/Series:/tv'
      - '/mnt/share/Media/Movies:/movies'
    restart: unless-stopped
    image: 'lscr.io/linuxserver/plex:latest'