---
version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
      - CLI_ARGS= #optional
    volumes:
      - /home/roman/configs/duplicati:/config
      - /home/roman:/backups_user
      - /etc/nginx/sites-enabled:/backups_nginx
      - /mnt/backup/:/destination
    ports:
      - 8017:8200
    restart: unless-stopped
