version: '3.3'
services:
  navidrome:
    container_name: navidrome
    restart: unless-stopped
    volumes:
      - '/mnt/share/Music:/music'
      - '/home/roman/configs/navidrome:/data'
    ports:
      - '8011:4533'
    environment:
      - ND_LOGLEVEL=info
    image: 'deluan/navidrome:latest'