version: '3.3'
services:
  portainer-ce:
    ports:
      - '8000:8000'
      - '8002:9000'
    container_name: portainer
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/home/roman/configs/portainer:/data'
    image: 'portainer/portainer-ce:latest'
