version: "3.3"
services:
  matomo:
    container_name: matomo
    image: matomo
    ports:
      - 8003:80
    environment:
      - MATOMO_DATABASE_HOST=matomo_db
    volumes:
      - /home/roman/configs/stats/data/stats/config:/var/www/html/config:rw
      - /home/roman/configs/stats/data/stats/logs:/var/www/html/logs
      - /home/roman/configs/stats/data/stats/matomo:/var/www/html
    env_file:
      - ./db.env
    networks:
      - net
    depends_on:
      - matomo_db
    restart: unless-stopped
  matomo_db:
    container_name: matomo_db
    image: mariadb
    command: --max-allowed-packet=64MB
    volumes:
      - /home/roman/configs/stats/data/db:/var/lib/mysql
    env_file:
      - ./db.env
    networks:
      - net
    restart: unless-stopped
networks:
  net:
    driver: bridge