version: '3.3'
services:
  linuxserver:
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    ports:
      - '7002:8384'
      - '22000:22000/tcp'
      - '22000:22000/udp'
      - '21027:21027/udp'
    volumes:
      - '/home/roman/configs/syncthing:/config'
      - '/mnt/share:/Sync'
    restart: unless-stopped
    image: lscr.io/linuxserver/syncthing