---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - USER=user #optional
      - PASS=test #optional
      - WHITELIST= #optional
    volumes:
      - /home/roman/configs/transmission:/config
      - /mnt/media/Downloads:/downloads
      - /mnt/share/Media/Torrents:/watch
    ports:
      - 8009:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
